[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "salted-espresso"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "ase",
    "sphericart",
    "scipy",
]
description = "Tools to construct callable electronic densities from QM outputs"
readme = "README.md"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = [
    "salted_espresso",
    "salted_espresso.*",
    "electronic_density",
    "electronic_density.*",
    "ri_basis",
    "ri_basis.*",
    "projections",
    "projections.*",
]

[tool.pytest.ini_options]
testpaths = ["tests"]