[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "salted_espresso"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "ase",
]

[tool.setuptools.packages.find]
where = [".."]
include = ["salted_espresso*"]
exclude = ["salted_espresso.tests*"]

[tool.pytest.ini_options]
pythonpath = [".."]
testpaths = ["tests"]
